import Head from "next/head";
import Image from "next/image";
import NavbarMobile from "../components/Navbar/NavbarMobile";
import Timeline from "../components/Timeline/Timeline";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavbarMobile />
      <main className="relative top-16 m-auto max-w-3xl">
        <div>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Blanditiis
          dicta consequatur mollitia cumque autem quidem in, quod suscipit? Esse
          excepturi ex veniam iste, obcaecati omnis quidem praesentium eos ullam
          consectetur. Lorem ipsum dolor sit, amet consectetur adipisicing elit.
          Blanditiis dicta consequatur mollitia cumque autem quidem in, quod
          suscipit? Esse excepturi ex veniam iste, obcaecati omnis quidem
          praesentium eos ullam consectetur. Lorem ipsum dolor sit, amet
          consectetur adipisicing elit. Blanditiis dicta consequatur mollitia
          cumque autem quidem in, quod suscipit? Esse excepturi ex veniam iste,
          obcaecati omnis quidem praesentium eos ullam consectetur. Lorem ipsum
          dolor sit, amet consectetur adipisicing elit. Blanditiis dicta
          consequatur mollitia cumque autem quidem in, quod suscipit? Esse
          excepturi ex veniam iste, obcaecati omnis quidem praesentium eos ullam
          consectetur. Lorem ipsum dolor sit, amet consectetur adipisicing elit.
          Blanditiis dicta consequatur mollitia cumque autem quidem in, quod
          suscipit? Esse excepturi ex veniam iste, obcaecati omnis quidem
          praesentium eos ullam consectetur. Lorem ipsum dolor sit, amet
          consectetur adipisicing elit. Blanditiis dicta consequatur mollitia
          cumque autem quidem in, quod suscipit? Esse excepturi ex veniam iste,
          obcaecati omnis quidem praesentium eos ullam consectetur.
        </div>
        <Timeline />
      </main>
    </div>
  );
}
